### ISSUE TITLE
Commit `41e1222` breaks Neovim 0.5.1

### ISSUE THREAD

**Issue by axieax** [luukvbaal/stabilize.nvim#10]
Nested autocmd for Trouble.nvim causes the following message to appear everytime you start up Neovim 0.5.1:
![image](https://user-images.githubusercontent.com/62098008/144579251-aa5cebe4-5c97-433d-bcc1-cef3c954c9d2.png)

My current config is:
```lua
require("stabilize").setup({
  nested = "QuickFixCmdPost, User LspDiagnosticsChanged",
})
```
I am aware of the breaking change for 0.6 which renames LspDiagnosticsChanged -> Diagnostics Changed, and have tried various combinations to no avail:
- QuickFixCmdPost, User LspDiagnosticsChanged
- QuickFixCmdPost, User DiagnosticsChanged
- QuickFixCmdPost,LspDiagnosticsChanged
- QuickFixCmdPost,DiagnosticsChanged

**Comment by luukvbaal** [comment]
I suppose we can keep 0.5 compatibility by moving the buffer wildcard to user config. The correct event name for 0.6 is `DiagnosticChanged`, not `DiagnosticsChanged` btw.

**Comment by axieax** [comment]
Oh yeah oops typo 😅
Yeah that sounds like a good solution for now :D
