### ISSUE TITLE
Neovim not closed when trouble.nvim is the last existing buffer

### ISSUE THREAD

**Issue by hanspinckaers** [luukvbaal/stabilize.nvim#12]
Trouble.nvim has a feature that neovim is closed when it's the last buffer, so you never have only Trouble.nvim. However, this plugin breaks that functionality. 

To reproduce: have a file open with trouble.nvim in a split. Try to quit neovim.

Thanks,
Hans

**Comment by hanspinckaers** [comment]
It works if I remove `BufEnter` from `eventignore` here:

https://github.com/luukvbaal/stabilize.nvim/blob/191d102fd48d9067c5be267b72da4ac28051dc12/lua/stabilize.lua#L25

**Comment by luukvbaal** [comment]
Issue should be gone with the latest commit, please confirm.

**Comment by hanspinckaers** [comment]
Yes, it works! Thanks!
