### ISSUE TITLE
Bug with ts-context integration

### ISSUE THREAD

**Issue by axieax** [luukvbaal/stabilize.nvim#13]
Hi!
I'm using [nvim-treesitter-context](https://github.com/romgrk/nvim-treesitter-context) and it seems that everytime that floating window is open and I `PackerCompile`, Stablize throws the following error:
![image](https://user-images.githubusercontent.com/62098008/146660882-44009283-76cb-4eec-bf6b-341a91f3427f.png)

**Comment by luukvbaal** [comment]
Can you check whether the issue still occurs on https://github.com/luukvbaal/stabilize.nvim/commit/e97de689cbebb5a58603905db7f09107d86a147b?

**Comment by axieax** [comment]
That fixed it TYSM!! 😍😍
