### ISSUE TITLE
requires nightly now ?

### ISSUE THREAD

**Issue by desdic** [luukvbaal/stabilize.nvim#15]
After updating this morning there is a message that augroup only works with neovim nightly and yes it fails

```
                    Error detected while processing /home/kgn/src/private/neovim/init.lua:
E5113: Error while calling lua chunk: .../site/pack/packer/start/stabilize.nvim/lua/stabilize.lua:82: attempt to call field 'nvim_create_augroup' (a nil value)
stack traceback:
        .../site/pack/packer/start/stabilize.nvim/lua/stabilize.lua:82: in function 'setup'
        /home/kgn/.config/nvim/lua/config/stabilize.lua:8: in main chunk
        [C]: in function 'require'
        /home/kgn/.config/nvim/init.lua:12: in main chunk
```

is it supposed to only work with nightly from now on ? I use 0.6.1 but get this error

**Comment by CKolkey** [comment]
Seeing as it's now using the autocmd api, I think the answer is yes:
https://github.com/luukvbaal/stabilize.nvim/commit/92461da24419ee5476d1541018929e231bf3522d

You can pin to the https://github.com/luukvbaal/stabilize.nvim/commit/a1cd8b530475061753fa246195ddf4f2330c674f commit if you want to keep using 0.6.1

**Comment by luukvbaal** [comment]
Seeing as though the plugin is quite stable I indeed thought users would have no issues pinning a commit. 

I reverted the change and made a 0.7 branch instead to avoid further issues.
