### ISSUE TITLE
Cursor jumps after last-place

### ISSUE THREAD

**Issue by axieax** [luukvbaal/stabilize.nvim#16]
Seems like commit 2bce92ce2e37f4a766bd2c92ba77be92f0e9bfdd causes the cursor to jump to the top of the file, breaking plugins / BufReadPost autocmds which set the cursor to the last location on the file.

**Comment by luukvbaal** [comment]
Could you describe how to reproduce? Are you talking about the first file/files you open, when opening a new split?

**Comment by luukvbaal** [comment]
I'm not sure why the cursor position would be set/restore when running `nvim <file>` or how the behavior would have changed with that commit. Is that what you're experiencing or is it something else?

**Comment by axieax** [comment]
It seems to only occur when opening nvim to a file. Opening files in nvim after everything is loaded seems to work fine.

## Without stabilize

https://user-images.githubusercontent.com/62098008/167412786-62f3c020-19de-4a55-914c-16012c687b09.mp4

## With stabilize

https://user-images.githubusercontent.com/62098008/167412829-5b562e92-e25c-4455-b590-73d56374f4ee.mp4

As you can see, the cursor initially gets restored to the expected position, before quickly jumping to the top of the file. Perhaps this is due to some autocmd firing right after BufReadPost?

**Comment by luukvbaal** [comment]
I can't reproduce with BufReadPost restore autocmd btw. I assume you're using the nvim-lastplace plugin? Could you try moving the plugin after stabilize in your load order? Are you sure the behavior is new with the commit you mentioned?

**Comment by luukvbaal** [comment]
This seems to work fine with this plugin:

```vim
autocmd BufReadPost *
     \ if line("'\"") > 0 && line("'\"") <= line("$") |
     \   exe "normal! g`\"" |
     \ endif
```
Not sure what the conflict is with nvim-lastplace

**Comment by axieax** [comment]
Are you able to reproduce this with nvim-lastplace? I've tried replacing it with that autocmd and it also causes the same behaviour for me. Also, moving the plugin order doesn't resolve anything, and yes everything works if I use the commit before (786c818d7258b783afc192ac287b4365c5596dcf).

**Comment by axieax** [comment]
Here's a minimal config:

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

set termguicolors

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'luukvbaal/stabilize.nvim'
call plug#end()
PlugInstall | quit

" Return to last edit position when opening files (You want this!)
autocmd BufReadPost *
     \ if line("'\"") > 0 && line("'\"") <= line("$") |
     \   exe "normal! g`\"" |
     \ endif

lua << EOF
require("stabilize").setup()
EOF
```

**Comment by luukvbaal** [comment]
That minimal config restores the last position for me🤷‍️

**Comment by luukvbaal** [comment]
Both on nightly and on 0.7, so that's not it either. Idk what could be causing this difference in behavior.

**Comment by axieax** [comment]
My apologies, impatient.nvim cached my config so minimal config wasn't very accurate. Not sure if it's due to another plugin, but it does work before that offending commit for some reason, whether I use nvim-lastplace or the autocmd.

**Comment by axieax** [comment]
Found the issue :))

**Comment by luukvbaal** [comment]
Sorry, hadn't had the time yet to look into it further. Thanks for resolving it!

**Comment by axieax** [comment]
Thanks for all your support :))
