### ISSUE TITLE
Deprecation notice markdown problem

### ISSUE THREAD

**Issue by rewhile** [luukvbaal/stabilize.nvim#20]
If you hover on the first line the link is invalid
![image](https://user-images.githubusercontent.com/56817415/194312136-aa485478-382b-4d3e-baeb-9e2678b5ad06.png)

I guess you should wrap it around like this `[https://github.com/neovim/neovim/pull/19243](https://github.com/neovim/neovim/pull/19243)`

**Comment by luukvbaal** [comment]
Thanks, I (force) pushed a fix. I think wrapping it like you suggested would block the issue preview hover popup github adds.
