### ISSUE TITLE
Failed to  switch to window

### ISSUE THREAD

**Issue by ghost** [luukvbaal/stabilize.nvim#5]
I'm currently working on the [`ataraxis.lua`](https://github.com/henriquehbr/ataraxis.lua) plugin, which is basically a distraction-free mode, the way it works, is by creating 2 buffers on each side of the editor

Whenever i try to use `stabilize.nvim` with it, i receive the following error message:

```
Error detected while processing /home/hbr/.config/nvim/init.lua:
E5113: Error while calling lua chunk: ...im/site/pack/paqs/start/stabilize.nvim/lua/stabilize.lua:82: Failed to
 switch to window 1001
```

I'm not sure if it's something related to the order that these plugins must be loaded, but i had no luck trying to figure it out, any clue of what might be happening?

**Comment by luukvbaal** [comment]
I know the plugin, I have it installed but exclusively use it for writing emails with neomutt. I haven't encountered any errors but perhaps there has been a regression. I'll check if I can reproduce later.

**Comment by luukvbaal** [comment]
I checked it out but I can't reproduce it in my setup. Running `TZAtaraxis` produces no such error. Could you try to provide a minimal setup to reproduce this?

**Comment by luukvbaal** [comment]
This plugin loops over the currently open windows to restore the topline and cursor position. That error implies that while looping over the windows returned by `api.nvim_tabpage_list_wins()` it is somehow closed/invalidated but I'm not sure why that would happen.

The error might be avoided with `api.nvim_win_is_valid()` but I'd like to be able to reproduce it first.

**Comment by luukvbaal** [comment]
I see your error actually happens in the `setup()` function so load order might have something to do with it but since neovim is single threaded I'm not sure how a window gets invalidated while looping over `api.nvim_list_wins()`.

**Comment by luukvbaal** [comment]
Wait, I actually have [`TreuZen.nvim`](https://github.com/Pocco81/TrueZen.nvim) installed, not your plugin, my bad. I'll check if I can reproduce with your plugin.

Edit: what's the difference between the two btw?:)

**Comment by ghost** [comment]
`ataraxis.lua` has a smaller codebase and it's simpler overall, containing less features, aimed more towards the philosophy of _"do one thing, and do it well"_

**Comment by luukvbaal** [comment]
It doesn't work for me though, I'm getting:

    Error detected while processing BufEnter Autocommands for "{leftbuffer,rightbuffer}":
    E5108: Error executing lua [string "v:lua"]:1: attempt to call global 'quit_buffer_or_nvim' (a nil value)

**Comment by ghost** [comment]
I just pushed a new branch for reproducing this issue with a fix for the bug you mentioned, try cloning, changing to the `repro/stabilize-nvim` branch, commenting out `ataraxis` initialization code from your config, and running:

```bash
nvim --cmd "set rtp+=. | lua require 'ataraxis'.setup()"
```

This will run the local version of ataraxis instead of the one installed on your main config, remember to be on the root directory of the cloned repo when running this command, otherwise it won't work

**Comment by luukvbaal** [comment]
Okay I can reproduce, I guess you set some property that disallows focusing the left/right windows. Could you point me in the right direction then I might be able to check for that before trying to switch to it.

**Comment by ghost** [comment]
Sure, there's an autocommand for `BufEnter` on `autocommands.lua` that focuses back the main window whenever you try to focus on any of those side windows, you can disable it by removing the autocommand (line 5)

**Comment by luukvbaal** [comment]
I see, I suppose adding `BufEnter` to `eventignore` while looping over the windows will  avoid the error. 

I guess that's a fine change to stabilize.nvim for compatability with your plugin but perhaps even desirable in general.

**Comment by ghost** [comment]
I really thought this would be one of those "really hard to figure out problem", many thanks for your time and support, i really appreciate it :)

Keep up the great job! this plugin is a really nice addition to neovim's ecosystem

**Comment by luukvbaal** [comment]
Thanks, please confirm the fix.

**Comment by ghost** [comment]
Yep, it's working as expected now
