### ISSUE TITLE
This plugin breaks filetype detection when loading a session

### ISSUE THREAD

**Issue by b0o** [luukvbaal/stabilize.nvim#8]
The breakage occurred in the latest commit (cad28c53f0497b56836ca89ede404c7e57df25c8).

Steps to reproduce:

1. Open a few files that have syntax highlighting in multiple nvim windows
2. Create a session: `:mksession /tmp/repro`
3. Quit nvim
4. Launch nvim with the `-S` option: `nvim -S /tmp/repro`
5. The session should be loaded, the files should have no syntax highlighting

Expected behavior:

1. Checkout 10bb37c82e94122be082651ee6ee58b5b2e51cb5 of this repository
2. Repeat the steps above, the files should have proper syntax highlighting

Based on the changes made in cad28c53f0497b56836ca89ede404c7e57df25c8, this issue likely extends to anything relying on events when a session is loading. Also note that session loading can happen at any time, not only during startup, and this issue still applies in those cases.

**Comment by b0o** [comment]
This should be helpful in fixing the issue ([`:help SessionLoad-variable`](https://neovim.io/doc/user/starting.html#SessionLoad-variable)):

```help
The |SessionLoadPost| autocmd event is triggered after a session file is
loaded/sourced.
						*SessionLoad-variable*
While the session file is loading the SessionLoad global variable is set to 1.
Plugins can use this to postpone some work until the SessionLoadPost event is
triggered.
```

**Comment by luukvbaal** [comment]
Thanks for reporting. I never noticed any issues myself because I lazy-load this plugin on `CursorHold`.

Could you check if https://github.com/luukvbaal/stabilize.nvim/commit/a04ffdb589193268b716cebb7dc9d272b52eed3a fixes the issue?

**Comment by luukvbaal** [comment]
> Also note that session loading can happen at any time, not only during startup, and this issue still applies in those cases.

Didn't read this part, I guess https://github.com/luukvbaal/stabilize.nvim/commit/a04ffdb589193268b716cebb7dc9d272b52eed3a won't fix anything then.

Think I'll just revert https://github.com/luukvbaal/stabilize.nvim/commit/cad28c53f0497b56836ca89ede404c7e57df25c8.

**Comment by b0o** [comment]
I just tested a04ffdb and it seems to work perfectly in both cases 👍
