### ISSUE TITLE
Error with kyazdani42/nvim-tree.lua

### ISSUE THREAD

**Issue by MunifTanjim** [luukvbaal/stabilize.nvim#9]
**Setup**:

```lua
require("stabilize").setup({
  force = false,
})
```

**Reproduction Step**:

- Run `nvim`
- Open a long file (with 60 LOC)
- Put your cursor on Line 50
- Open nvim-tree
- Open a short file (with 20 LOC)
- Error is printed.

**Error**:

```
Error executing vim.schedule lua callback: ...ocal/share/nvim/plugged/stabilize.nvim/lua/stabilize.lua:50: Cursor position outside buffer
stack traceback:
        [C]: in function 'nvim_win_set_cursor'
        ...ocal/share/nvim/plugged/stabilize.nvim/lua/stabilize.lua:50: in function <...ocal/share/nvim/plugged/stabilize.nvim/lua/stabilize.lua:26>
```

![Kapture 2021-11-20 at 00 33 22](https://user-images.githubusercontent.com/8050659/142673894-2466d19b-87ad-4066-a3fe-b980ec780804.gif)

**Comment by luukvbaal** [comment]
Wasn't able to reproduce but I think https://github.com/luukvbaal/stabilize.nvim/commit/d7fdd1d79c07e37361f6f75392bd062d511cfee5 should prevent the error, please confirm.

**Comment by MunifTanjim** [comment]
Yes, that solved it. Thanks 🎉
